"""
email_client.py — 100% free email sending (via Gmail SMTP) for diet plans & fee reminders.

Setup (free, 2 minutes):
1. Open your Gmail account -> Google Account -> Security -> 2-Step Verification (turn it on if it's off)
2. Scroll down in Security to the "App Passwords" section -> create a new app password (any name works)
3. Copy the 16-character password and paste it into the app's sidebar "Email Settings" (your normal Gmail
   password will NOT work, only the App Password will)
4. This only uses Gmail's free SMTP relay — no paid API/service is required.
"""

import smtplib
import re
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText


def send_email(sender_email, sender_app_password, to_email, subject, html_body,
               smtp_server="smtp.gmail.com", smtp_port=465):
    """Sends one HTML email via Gmail's free SMTP relay. Returns (success: bool, error: str|None)."""
    if not sender_email or not sender_app_password:
        return False, "⚠️ Please open 'Email Settings' in the sidebar first and enter your Gmail address + App Password."
    if not to_email or not to_email.strip():
        return False, "⚠️ This student's email address is not registered. Add it in Student Management."

    msg = MIMEMultipart("alternative")
    msg["Subject"] = subject
    msg["From"] = sender_email
    msg["To"] = to_email
    msg.attach(MIMEText(html_body, "html"))

    try:
        with smtplib.SMTP_SSL(smtp_server, smtp_port, timeout=20) as server:
            server.login(sender_email, sender_app_password)
            server.sendmail(sender_email, to_email, msg.as_string())
        return True, None
    except smtplib.SMTPAuthenticationError:
        return False, ("❌ Gmail login failed. Your normal Gmail password does not work — "
                        "create a 16-digit password from Google Account > Security > App Passwords and enter that instead.")
    except Exception as e:
        return False, f"❌ Email bhejne me error: {e}"


def markdown_to_simple_html(text):
    """Light markdown -> HTML so AI-generated plan_text (headings/bullets) renders decently in inboxes."""
    lines = (text or "").split("\n")
    html_lines = []
    in_list = False
    for raw in lines:
        line = raw.strip()
        if line.startswith("### "):
            if in_list:
                html_lines.append("</ul>"); in_list = False
            html_lines.append(f"<h4 style='margin:14px 0 4px;'>{line[4:]}</h4>")
        elif line.startswith("## "):
            if in_list:
                html_lines.append("</ul>"); in_list = False
            html_lines.append(f"<h3 style='margin:16px 0 6px;'>{line[3:]}</h3>")
        elif line.startswith("# "):
            if in_list:
                html_lines.append("</ul>"); in_list = False
            html_lines.append(f"<h2 style='margin:18px 0 8px;'>{line[2:]}</h2>")
        elif line.startswith("- ") or line.startswith("* "):
            if not in_list:
                html_lines.append("<ul style='margin:4px 0;'>"); in_list = True
            html_lines.append(f"<li>{re.sub(r'^[-*]\\s+', '', line)}</li>")
        elif line == "":
            if in_list:
                html_lines.append("</ul>"); in_list = False
            html_lines.append("<br>")
        else:
            if in_list:
                html_lines.append("</ul>"); in_list = False
            html_lines.append(f"<p style='margin:4px 0;'>{line}</p>")
    if in_list:
        html_lines.append("</ul>")
    return "\n".join(html_lines)


def diet_plan_email_body(student, diet_type, goal, plan_text):
    body_html = markdown_to_simple_html(plan_text)
    return f"""
    <div style="font-family:Arial,sans-serif;max-width:640px;margin:auto;color:#222;">
        <div style="background:#1b2a4a;color:#FFD166;padding:16px 20px;border-radius:8px 8px 0 0;">
            <h2 style="margin:0;">🏏 Shree Shyam Cricket Academy</h2>
            <p style="margin:4px 0 0;color:#fff;">AI Diet Plan for {student.get('name')}</p>
        </div>
        <div style="border:1px solid #eee;border-top:none;padding:20px;border-radius:0 0 8px 8px;">
            <p><b>Diet Type:</b> {diet_type} &nbsp;|&nbsp; <b>Goal:</b> {goal}</p>
            <hr style="border:none;border-top:1px solid #eee;">
            {body_html}
            <hr style="border:none;border-top:1px solid #eee;">
            <p style="color:#888;font-size:12px;">This plan was generated by GroqCloud AI. For any
            medical ya allergy concern ho to academy coach se poochein.<br>
            — Shree Shyam Cricket Academy, Bahadurgarh</p>
        </div>
    </div>
    """


def fee_reminder_email_body(student, fee):
    is_overdue = fee.get("_effective_status") == "Overdue"
    status_word = "OVERDUE" if is_overdue else "due soon"
    color = "#e63946" if is_overdue else "#f4a300"
    return f"""
    <div style="font-family:Arial,sans-serif;max-width:640px;margin:auto;color:#222;">
        <div style="background:#1b2a4a;color:#FFD166;padding:16px 20px;border-radius:8px 8px 0 0;">
            <h2 style="margin:0;">🏏 Shree Shyam Cricket Academy</h2>
            <p style="margin:4px 0 0;color:#fff;">Fees Reminder</p>
        </div>
        <div style="border:1px solid #eee;border-top:none;padding:20px;border-radius:0 0 8px 8px;">
            <p>Dear <b>{student.get('name')}</b>,</p>
            <p>Your academy fees are <b style="color:{color};">{status_word}</b>.</p>
            <table style="border-collapse:collapse;width:100%;">
                <tr><td style="padding:6px;border:1px solid #eee;">Month</td><td style="padding:6px;border:1px solid #eee;">{fee.get('month')}</td></tr>
                <tr><td style="padding:6px;border:1px solid #eee;">Amount</td><td style="padding:6px;border:1px solid #eee;">₹{fee.get('amount')}</td></tr>
                <tr><td style="padding:6px;border:1px solid #eee;">Due Date</td><td style="padding:6px;border:1px solid #eee;">{fee.get('due_date')}</td></tr>
            </table>
            <p style="margin-top:16px;">Please contact the academy office/coach as soon as possible to pay the feeswayein.</p>
            <p style="color:#888;font-size:12px;">— Shree Shyam Cricket Academy, Bahadurgarh</p>
        </div>
    </div>
    """
